# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: license-check.txt|^(docs/|notebooks/|data/|src/secrets/|src/static/|src/templates/test)
default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-builtin-literals
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
    - id: check-toml
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: "5.11.4"
    hooks:
    - id: isort
      args: ["--profile", "black", "."]
  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
    - id: black
      args: [--line-length=120]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==3.2.0]
        #args: [--no-strict-optional, --ignore-missing-imports]
